
const esbuild = require('esbuild');
const fg = require('fast-glob');

// import copy from 'esbuild-plugin-copy';


(async () => {
  const copy = (await import('esbuild-plugin-copy')).default;


  await esbuild.build({
    entryPoints: fg.sync(['src/*.ts', 'src/*.js']),
    bundle: true,
    format: 'iife', // iife
    target: ['es2020'],
    platform: 'browser',
    outdir: './dist',
    minify: true,
    plugins: [
      copy({
        assets: { from: 'src/cict.conf', to: 'cict.conf' },
      })
    ],
    external: ['fs', 'path', 'got', 'tough-cookie', 'iconv-lite',],  // ✅ 这些模块不会被打包
    banner: {
      js: 
`/*     * This is a generated file. Do not edit it manually.
        Generated by esbuild.
*/`
    }
  })

})();
